POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test2",
    "author": "Wed, 21 Oct 2015 18:27:50 GMT",
    "url": "localhost",
    "userId":"609291cf5a9ea3020a1be746",
    "likes": 10
}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{

    "username": "sean",
    "name": "sean",
    "password": "psssa"
        
}

###
GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

###

PUT http://localhost:3001/api/blogs/608e9202a31dcc12cc3096d8 HTTP/1.1
content-type: application/json

{
    "title": "test2",
    "author": "Wed, 21 Oct 2015 18:27:50 GMT",
    "url": "localhost",
    "likes": 13
}

###

GET http://localhost:3001/api/blogs HTTP/1.1

###

GET http://localhost:3001/api/blogs/608e9202a31dcc12cc3096d8 HTTP/1.1


###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "sean",
    "password": "psssa"
}

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlYW4iLCJpZCI6IjYwOGZlNTk4MjljNjBiMmE2ZDAyYjAwZCIsImlhdCI6MTYyMDA0MzkxMX0.Y6MbOdqe3Fmvs09Nv90h-k5tajt7hy-beIdrlJyLGoc

{
    "content": "API Auth Test",
    "important": true
}